# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: virrasch <virrasch@student.42malaga.c      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/04/22 12:13:14 by virrasch          #+#    #+#              #
#    Updated: 2025/04/22 12:23:09 by virrasch         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# NAME - COMPILER - FLAGS #

NAME = libft.a
CC = cc
FLAGS= -Wall -Wextra -Werror

# SOURCES - OBJECTS #

SRC = ft_isalnum.c ft_isalpha.c ft_isascii.c ft_isdigit.c ft_isprint.c ft_strlen.c
OBJ = $(SRC:.c=.o)

# MAIN RULE #

all: $(NAME)

$(NAME):$(OBJ)

